---
- name: Join Linux server to AD Domain
  hosts: linux
  become: true
  vars:
    domain_name: "lab.local"
    ad_user: "Administrator"
    ad_password: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  tasks:
    - name: Install required packages
      package:
        name: "{{ common_packages }}"
      vars:
        common_packages:
          - realmd
          - oddjob
          - oddjob-mkhomedir
          - sssd
          - adcli
          - samba-common-tools
      when: ansible_distribution == 'Amazon'
      
    - name: Ensure system is using AD DNS
      become: yes
      lineinfile:
        path: /etc/resolv.conf
        regexp: '^nameserver'
        line: "nameserver {{ windows_dns }}"

    - name: Discover the AD domain
      command: realm discover {{ domain_name }}
      register: realm_discover
      changed_when: false

    - name: Join the Linux instance to the domain
      command: >
        realm join --user={{ ad_user }}
        {{ domain_name }}
      args:
        stdin: "{{ ad_password }}"
      register: realm_join
      changed_when: "'successfully enrolled' in realm_join.stdout"

    - name: Ensure SSSD service is started
      service:
        name: sssd
        state: started
        enabled: yes

    - name: Allow domain users to log in
      command: realm permit --all
