---
- name: Promote Windows Server to Domain Controller
  hosts: windows
  gather_facts: no
  vars:
    domain_name: "lab.local"
    domain_netbios: "LAB"
    safe_mode_password: "P@ssw0rd123!"
  tasks:
    - name: Install AD-Domain-Services feature
      win_feature:
        name: AD-Domain-Services
        include_management_tools: yes
        state: present

    - name: Promote to Domain Controller
      win_domain:
        dns_domain_name: "{{ domain_name }}"
        domain_netbios_name: "{{ domain_netbios }}"
        safe_mode_password: "{{ safe_mode_password }}"
        domain_admin_user: "Administrator"
        domain_admin_password: "{{ ansible_password }}"
      register: domain_result

    - name: Reboot after domain promotion
      win_reboot:
      when: domain_result.changed
